### ISSUE TITLE
`Booking` dashboard page

### ISSUE THREAD

**Issue by Blastd** [APSfurizon/fz-frontend#13]
Add a Booking dashboard page, where the user can view the current con's booking data, or view the store link.
Might be a good idea to also list every issue with the account the user might have (@stranck 's idea)

**Comment by stranck** [comment]
For now for sure we have the `MEMBERSHIP_MULTIPLE_DONE, MEMBERSHIP_MISSING, ORDER_MULTIPLE_DONE` documented in the class `net.furizon.backend.feature.pretix.ordersworkflow.OrderWorkflowErrorCode` and verbally explained in the documentation of the `/orders-workflow/order-sanity-check` method. There may be errors in room (where, for example, sanity checks unconfirm your room), but this is definitely for the future and we don't need them rn

**Comment by Blastd** [comment]
Finished the booking page:
It features the order's data + a list of potential errors and data warnings, as well as an animated countdown and a popup button when the bookings open
